FROM registry.redhat.io/ubi8/nodejs-12
USER 0

# ENV BUILD_DEPS='libica-utils openssl libssl-dev openssl-ibmca'

# RUN set -x \
# &&  apt-get update \
# &&  apt-get install -y $BUILD_DEPS --no-install-recommends \
# &&  rm -rf /var/lib/apt/lists/* \
# &&  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false

# RUN set -x \
# &&  tee -a /etc/ssl/openssl.cnf < /usr/share/doc/openssl-ibmca/examples/openssl.cnf.sample\
# &&  sed -i -r 's/openssl_conf = default_conf/openssl_conf = openssl_def/' /etc/ssl/openssl.cnf

RUN mkdir -p /home/0/app && chown -R 0:0 /home/0/app

RUN mkdir -p /home/0/app/builtAssets && chmod 777 /home/0/app/builtAssets
# Create app directory
WORKDIR /home/0/app



# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
# COPY --chown=0:0 ../package*.json ./
COPY --chown=0:0 package*.json ./
RUN npm install

# Bundle app source
# COPY --chown=0:0 ../ .
COPY --chown=0:0 . .

EXPOSE 8080
CMD [ "npm", "start" ]
