FROM ppc64le/node:12-buster 

USER node

# Create app directory
WORKDIR /usr/src/app

RUN chown -R node:node /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY --chown=node:node ../package*.json ./

RUN npm install

# Bundle app source
COPY --chown=node:node ../ .

EXPOSE 8080
CMD [ "npm", "start" ]
